import type {
  Room,
  Reservation,
  Invoice,
  Hotel,
  User,
  DashboardStats,
  ApiKey,
  RoomType,
  Client,
  Newsletter,
} from "./types";

export const mockHotels: Hotel[] = [
  {
    id: "1",
    name: "Hôtel Ivoire Palace",
    address: "Plateau, Rue du Commerce",
    city: "Abidjan",
    phone: "+225 07 00 00 00 01",
    email: "contact@ivoirepalace.ci",
    totalRooms: 45,
  },
  {
    id: "2",
    name: "Résidence La Corniche",
    address: "Cocody, Boulevard Latrille",
    city: "Abidjan",
    phone: "+225 07 00 00 00 02",
    email: "info@lacorniche.ci",
    totalRooms: 28,
  },
];

export const mockUser: User = {
  id: "1",
  name: "Kouadio Yao",
  email: "kouadio@ivoirepalace.ci",
  role: "admin",
  hotelId: "1",
};
export const mockRoomTypes: RoomType[] = [
  {
    id: "1",
    name: "Standard",
    description: "Chambre confortable avec toutes les commodités essentielles",
    basePrice: 15000,
    capacity: 2,
    amenities: ["Wi-Fi", "TV", "Climatisation", "Salle de bain privée"],
    image: "/standard-hotel-room.png",
  },
  {
    id: "2",
    name: "Deluxe",
    description: "Chambre spacieuse avec vue et équipements premium",
    basePrice: 25000,
    capacity: 2,
    amenities: [
      "Wi-Fi",
      'TV 55"',
      "Climatisation",
      "Mini-bar",
      "Coffre-fort",
      "Vue mer",
    ],
    image: "/deluxe-hotel-room.png",
  },
  {
    id: "3",
    name: "Suite",
    description: "Suite luxueuse avec salon séparé et services exclusifs",
    basePrice: 40000,
    capacity: 4,
    amenities: [
      "Wi-Fi",
      'TV 65"',
      "Climatisation",
      "Mini-bar",
      "Coffre-fort",
      "Salon",
      "Jacuzzi",
    ],
    image: "/luxury-hotel-suite.png",
  },
  {
    id: "4",
    name: "Penthouse",
    description: "Le summum du luxe avec terrasse panoramique",
    basePrice: 100000,
    capacity: 6,
    amenities: [
      "Wi-Fi",
      'TV 75"',
      "Climatisation",
      "Bar complet",
      "Coffre-fort",
      "Salon",
      "Jacuzzi",
      "Terrasse",
      "Butler",
    ],
    image: "/luxury-hotel-lobby.png",
  },
];

export const mockRooms: Room[] = [
  {
    id: "1",
    number: "101",
    type: "standard",
    status: "available",
    price: 25000,
    capacity: 2,
    floor: 1,
  },
  {
    id: "2",
    number: "102",
    type: "standard",
    status: "occupied",
    price: 25000,
    capacity: 2,
    floor: 1,
  },
  {
    id: "3",
    number: "103",
    type: "deluxe",
    status: "available",
    price: 45000,
    capacity: 2,
    floor: 1,
  },
  {
    id: "4",
    number: "104",
    type: "deluxe",
    status: "cleaning",
    price: 45000,
    capacity: 3,
    floor: 1,
  },
  {
    id: "5",
    number: "201",
    type: "standard",
    status: "occupied",
    price: 25000,
    capacity: 2,
    floor: 2,
  },
  {
    id: "6",
    number: "202",
    type: "suite",
    status: "available",
    price: 75000,
    capacity: 4,
    floor: 2,
  },
  {
    id: "7",
    number: "203",
    type: "suite",
    status: "maintenance",
    price: 75000,
    capacity: 4,
    floor: 2,
  },
  {
    id: "8",
    number: "204",
    type: "deluxe",
    status: "occupied",
    price: 45000,
    capacity: 2,
    floor: 2,
  },
  {
    id: "9",
    number: "301",
    type: "penthouse",
    status: "available",
    price: 150000,
    capacity: 6,
    floor: 3,
  },
  {
    id: "10",
    number: "302",
    type: "suite",
    status: "occupied",
    price: 75000,
    capacity: 4,
    floor: 3,
  },
];

export const mockReservations: Reservation[] = [
  {
    id: "1",
    guestName: "Awa Koné",
    guestEmail: "awa.kone@email.com",
    guestPhone: "+225 07 12 34 56 78",
    roomId: "2",
    roomNumber: "102",
    checkIn: "2025-01-08",
    checkOut: "2025-01-12",
    status: "checked-in",
    totalAmount: 100000,
    paidAmount: 100000,
    paymentMethod: "mobile-money",
    createdAt: "2025-01-05",
  },
  {
    id: "2",
    guestName: "Jean-Pierre Bamba",
    guestEmail: "jp.bamba@email.com",
    guestPhone: "+225 05 98 76 54 32",
    roomId: "5",
    roomNumber: "201",
    checkIn: "2025-01-09",
    checkOut: "2025-01-11",
    status: "checked-in",
    totalAmount: 50000,
    paidAmount: 25000,
    paymentMethod: "cash",
    createdAt: "2025-01-07",
  },
  {
    id: "3",
    guestName: "Marie Touré",
    guestEmail: "m.toure@email.com",
    guestPhone: "+225 01 23 45 67 89",
    roomId: "8",
    roomNumber: "204",
    checkIn: "2025-01-09",
    checkOut: "2025-01-14",
    status: "confirmed",
    totalAmount: 225000,
    paidAmount: 0,
    paymentMethod: "transfer",
    createdAt: "2025-01-06",
  },
  {
    id: "4",
    guestName: "Amadou Diallo",
    guestEmail: "a.diallo@email.com",
    guestPhone: "+225 07 11 22 33 44",
    roomId: "10",
    roomNumber: "302",
    checkIn: "2025-01-07",
    checkOut: "2025-01-09",
    status: "checked-in",
    totalAmount: 150000,
    paidAmount: 150000,
    paymentMethod: "card",
    createdAt: "2025-01-04",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "INV-001",
    reservationId: "1",
    guestName: "Awa Koné",
    amount: 100000,
    tax: 18000,
    total: 118000,
    status: "paid",
    dueDate: "2025-01-12",
    createdAt: "2025-01-08",
    items: [
      {
        description: "Chambre Standard (4 nuits)",
        quantity: 4,
        unitPrice: 25000,
        total: 100000,
      },
    ],
  },
  {
    id: "INV-002",
    reservationId: "2",
    guestName: "Jean-Pierre Bamba",
    amount: 50000,
    tax: 9000,
    total: 59000,
    status: "partial",
    dueDate: "2025-01-11",
    createdAt: "2025-01-09",
    items: [
      {
        description: "Chambre Standard (2 nuits)",
        quantity: 2,
        unitPrice: 25000,
        total: 50000,
      },
    ],
  },
  {
    id: "INV-003",
    reservationId: "3",
    guestName: "Marie Touré",
    amount: 225000,
    tax: 40500,
    total: 265500,
    status: "pending",
    dueDate: "2025-01-14",
    createdAt: "2025-01-09",
    items: [
      {
        description: "Chambre Deluxe (5 nuits)",
        quantity: 5,
        unitPrice: 45000,
        total: 225000,
      },
    ],
  },
];

export const mockStats: DashboardStats = {
  totalRooms: 10,
  availableRooms: 4,
  occupiedRooms: 4,
  cleaningRooms: 1,
  maintenanceRooms: 1,
  occupancyRate: 40,
  todayCheckIns: 3,
  todayCheckOuts: 2,
  monthlyRevenue: 2450000,
  pendingInvoices: 2,
};

export const mockApiKeys: ApiKey[] = [
  {
    id: "1",
    name: "Site Web Principal",
    key: "hm_live_k1a2b3c4d5e6f7g8h9i0",
    secret: "hm_secret_x9y8z7w6v5u4t3s2r1q0p9o8n7m6l5k4",
    hotelId: "1",
    permissions: [
      "reservations:read",
      "reservations:write",
      "rooms:read",
      "availability:read",
    ],
    createdAt: "2024-11-15",
    lastUsedAt: "2025-01-09",
    expiresAt: null,
    status: "active",
    requestsToday: 142,
    requestsTotal: 15420,
  },
  {
    id: "2",
    name: "Application Mobile",
    key: "hm_live_j9k8l7m6n5o4p3q2r1s0",
    secret: "hm_secret_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
    hotelId: "1",
    permissions: ["reservations:read", "availability:read"],
    createdAt: "2024-12-20",
    lastUsedAt: "2025-01-08",
    expiresAt: "2025-12-20",
    status: "active",
    requestsToday: 58,
    requestsTotal: 3250,
  },
  {
    id: "3",
    name: "Test Integration",
    key: "hm_test_t1e2s3t4k5e6y7h8e9r0",
    secret: "hm_secret_t1e2s3t4s5e6c7r8e9t0k1e2y3h4e5r6",
    hotelId: "1",
    permissions: ["reservations:read", "rooms:read", "availability:read"],
    createdAt: "2025-01-02",
    lastUsedAt: null,
    expiresAt: "2025-02-02",
    status: "active",
    requestsToday: 0,
    requestsTotal: 0,
  },
  {
    id: "4",
    name: "Ancien Site Web",
    key: "hm_live_o1l2d3k4e5y6r7e8v9o0",
    secret: "hm_secret_r1e2v3o4k5e6d7s8e9c0r1e2t3k4e5y6",
    hotelId: "1",
    permissions: [
      "reservations:read",
      "reservations:write",
      "rooms:read",
      "rooms:write",
      "availability:read",
    ],
    createdAt: "2024-06-10",
    lastUsedAt: "2024-10-15",
    expiresAt: null,
    status: "revoked",
    requestsToday: 0,
    requestsTotal: 45230,
  },
];
export const mockClients: Client[] = [
  {
    id: "1",
    name: "Awa Koné",
    email: "awa.kone@email.com",
    phone: "+225 07 12 34 56 78",
    address: "Cocody Riviera 3",
    city: "Abidjan",
    totalStays: 8,
    totalSpent: 850000,
    lastStay: "2025-01-12",
    firstStay: "2023-06-15",
    vipStatus: "gold",
    tags: ["Affaires", "Long séjour"],
    notes: "Préfère les chambres au dernier étage",
    newsletter: true,
    createdAt: "2023-06-15",
  },
  {
    id: "2",
    name: "Jean-Pierre Bamba",
    email: "jp.bamba@email.com",
    phone: "+225 05 98 76 54 32",
    address: "Plateau, Avenue Chardy",
    city: "Abidjan",
    totalStays: 3,
    totalSpent: 175000,
    lastStay: "2025-01-11",
    firstStay: "2024-08-20",
    vipStatus: "standard",
    tags: ["Tourisme"],
    newsletter: true,
    createdAt: "2024-08-20",
  },
  {
    id: "3",
    name: "Marie Touré",
    email: "m.toure@email.com",
    phone: "+225 01 23 45 67 89",
    address: "Marcory Zone 4",
    city: "Abidjan",
    totalStays: 12,
    totalSpent: 1450000,
    lastStay: "2025-01-14",
    firstStay: "2022-11-10",
    vipStatus: "platinum",
    tags: ["VIP", "Affaires", "Fidèle"],
    notes: "Cliente très fidèle, offrir upgrade quand possible",
    newsletter: true,
    createdAt: "2022-11-10",
  },
  {
    id: "4",
    name: "Amadou Diallo",
    email: "a.diallo@email.com",
    phone: "+225 07 11 22 33 44",
    address: "Yopougon Maroc",
    city: "Abidjan",
    totalStays: 5,
    totalSpent: 420000,
    lastStay: "2025-01-09",
    firstStay: "2024-02-28",
    vipStatus: "silver",
    tags: ["Famille"],
    newsletter: false,
    createdAt: "2024-02-28",
  },
  {
    id: "5",
    name: "Fatou Cissé",
    email: "fatou.cisse@email.com",
    phone: "+225 07 55 66 77 88",
    address: "Angré 8ème tranche",
    city: "Abidjan",
    totalStays: 2,
    totalSpent: 95000,
    lastStay: "2024-12-20",
    firstStay: "2024-10-05",
    vipStatus: "standard",
    tags: ["Tourisme"],
    newsletter: true,
    createdAt: "2024-10-05",
  },
  {
    id: "6",
    name: "Olivier Kouassi",
    email: "o.kouassi@business.ci",
    phone: "+225 07 99 88 77 66",
    address: "Cocody Ambassades",
    city: "Abidjan",
    totalStays: 15,
    totalSpent: 2100000,
    lastStay: "2025-01-08",
    firstStay: "2022-03-18",
    vipStatus: "platinum",
    tags: ["VIP", "Affaires", "Corporate"],
    notes: "PDG entreprise partenaire - tarif négocié",
    newsletter: true,
    createdAt: "2022-03-18",
  },
  {
    id: "7",
    name: "Sandrine Aka",
    email: "sandrine.aka@gmail.com",
    phone: "+225 05 44 33 22 11",
    city: "Yamoussoukro",
    totalStays: 4,
    totalSpent: 280000,
    lastStay: "2024-11-30",
    firstStay: "2024-01-15",
    vipStatus: "silver",
    tags: ["Événement", "Groupe"],
    newsletter: true,
    createdAt: "2024-01-15",
  },
  {
    id: "8",
    name: "Ibrahim Traoré",
    email: "ibrahim.t@hotmail.com",
    phone: "+225 01 77 88 99 00",
    address: "Treichville",
    city: "Abidjan",
    totalStays: 1,
    totalSpent: 45000,
    lastStay: "2025-01-05",
    firstStay: "2025-01-05",
    vipStatus: "standard",
    tags: ["Nouveau"],
    newsletter: false,
    createdAt: "2025-01-05",
  },
];

export const mockNewsletters: Newsletter[] = [
  {
    id: "1",
    subject: "Offre spéciale Saint-Valentin - 20% de réduction",
    content:
      "Célébrez l'amour dans notre établissement avec une offre exclusive...",
    status: "sent",
    recipients: 156,
    openRate: 42,
    clickRate: 18,
    sentAt: "2025-02-01",
    createdAt: "2025-01-28",
  },
  {
    id: "2",
    subject: "Nouvelle suite présidentielle disponible",
    content:
      "Découvrez notre toute nouvelle suite présidentielle avec vue panoramique...",
    status: "scheduled",
    recipients: 89,
    scheduledAt: "2025-01-20",
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    subject: "Programme de fidélité - Vos avantages exclusifs",
    content: "En tant que client fidèle, bénéficiez d'avantages exclusifs...",
    status: "draft",
    recipients: 0,
    createdAt: "2025-01-10",
  },
];
