import type { SaasHotelAccount, SaasSubscription, SaasPayment, SaasStats, SaasFeature } from "./types"

export const saasHotelAccounts: SaasHotelAccount[] = [
  {
    id: "hotel-1",
    name: "Hôtel Ivoire Palace",
    email: "contact@ivoirepalace.ci",
    phone: "+225 07 07 07 07 07",
    address: "Boulevard de la République",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    plan: "premium",
    status: "active",
    createdAt: "2024-01-15",
    trialEndsAt: null,
    totalRooms: 45,
    totalReservations: 1250,
    monthlyRevenue: 15000000,
    lastPaymentAt: "2025-05-01",
    nextBillingAt: "2025-06-01",
    ownerId: "owner-1",
    ownerName: "Koné Amadou",
    ownerEmail: "amadou.kone@ivoirepalace.ci",
  },
  {
    id: "hotel-2",
    name: "Résidence Les Palmiers",
    email: "info@palmiers.ci",
    phone: "+225 05 05 05 05 05",
    address: "Rue des Jardins",
    city: "Yamoussoukro",
    country: "Côte d'Ivoire",
    plan: "multi",
    status: "active",
    createdAt: "2024-03-20",
    trialEndsAt: null,
    totalRooms: 28,
    totalReservations: 680,
    monthlyRevenue: 8500000,
    lastPaymentAt: "2025-05-05",
    nextBillingAt: "2025-06-05",
    ownerId: "owner-2",
    ownerName: "Touré Fatou",
    ownerEmail: "fatou.toure@palmiers.ci",
  },
  {
    id: "hotel-3",
    name: "Auberge du Lac",
    email: "contact@aubergedulac.ci",
    phone: "+225 01 01 01 01 01",
    address: "Bord du Lac",
    city: "Bouaké",
    country: "Côte d'Ivoire",
    plan: "essentiel",
    status: "trial",
    createdAt: "2025-05-20",
    trialEndsAt: "2025-06-20",
    totalRooms: 12,
    totalReservations: 45,
    monthlyRevenue: 1200000,
    lastPaymentAt: null,
    nextBillingAt: "2025-06-20",
    ownerId: "owner-3",
    ownerName: "Diabaté Ibrahim",
    ownerEmail: "ibrahim@aubergedulac.ci",
  },
  {
    id: "hotel-4",
    name: "Grand Hôtel Cocody",
    email: "reservation@grandcocody.ci",
    phone: "+225 27 22 44 55 66",
    address: "Avenue Franchet d'Esperey",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    plan: "premium",
    status: "active",
    createdAt: "2023-11-10",
    trialEndsAt: null,
    totalRooms: 78,
    totalReservations: 3200,
    monthlyRevenue: 28000000,
    lastPaymentAt: "2025-05-01",
    nextBillingAt: "2025-06-01",
    ownerId: "owner-4",
    ownerName: "Ouattara Seydou",
    ownerEmail: "seydou@grandcocody.ci",
  },
  {
    id: "hotel-5",
    name: "Hôtel Sunset Beach",
    email: "info@sunsetbeach.ci",
    phone: "+225 07 89 45 23 12",
    address: "Route de Bassam",
    city: "Grand-Bassam",
    country: "Côte d'Ivoire",
    plan: "multi",
    status: "suspended",
    createdAt: "2024-06-15",
    trialEndsAt: null,
    totalRooms: 32,
    totalReservations: 520,
    monthlyRevenue: 0,
    lastPaymentAt: "2025-03-01",
    nextBillingAt: "2025-04-01",
    ownerId: "owner-5",
    ownerName: "Bamba Mariam",
    ownerEmail: "mariam@sunsetbeach.ci",
  },
  {
    id: "hotel-6",
    name: "Petit Hôtel Central",
    email: "petithotel@email.ci",
    phone: "+225 05 12 34 56 78",
    address: "Centre-ville",
    city: "San-Pédro",
    country: "Côte d'Ivoire",
    plan: "essentiel",
    status: "active",
    createdAt: "2024-09-01",
    trialEndsAt: null,
    totalRooms: 8,
    totalReservations: 180,
    monthlyRevenue: 950000,
    lastPaymentAt: "2025-05-10",
    nextBillingAt: "2025-06-10",
    ownerId: "owner-6",
    ownerName: "Coulibaly Jean",
    ownerEmail: "jean@petithotel.ci",
  },
]

export const saasSubscriptions: SaasSubscription[] = saasHotelAccounts.map((hotel) => ({
  id: `sub-${hotel.id}`,
  hotelId: hotel.id,
  hotelName: hotel.name,
  plan: hotel.plan,
  status: hotel.status === "trial" ? "trialing" : hotel.status === "suspended" ? "past_due" : "active",
  amount: hotel.plan === "essentiel" ? 10000 : hotel.plan === "multi" ? 20000 : 35000,
  currency: "XOF",
  billingCycle: "monthly",
  currentPeriodStart: "2025-05-01",
  currentPeriodEnd: "2025-06-01",
  cancelAtPeriodEnd: false,
}))

export const saasPayments: SaasPayment[] = [
  {
    id: "pay-1",
    hotelId: "hotel-1",
    hotelName: "Hôtel Ivoire Palace",
    amount: 35000,
    currency: "XOF",
    status: "succeeded",
    paymentMethod: "mobile-money",
    createdAt: "2025-05-01T10:30:00",
    description: "Abonnement Premium - Mai 2025",
  },
  {
    id: "pay-2",
    hotelId: "hotel-2",
    hotelName: "Résidence Les Palmiers",
    amount: 20000,
    currency: "XOF",
    status: "succeeded",
    paymentMethod: "mobile-money",
    createdAt: "2025-05-05T14:20:00",
    description: "Abonnement Multi - Mai 2025",
  },
  {
    id: "pay-3",
    hotelId: "hotel-4",
    hotelName: "Grand Hôtel Cocody",
    amount: 35000,
    currency: "XOF",
    status: "succeeded",
    paymentMethod: "card",
    createdAt: "2025-05-01T08:15:00",
    description: "Abonnement Premium - Mai 2025",
  },
  {
    id: "pay-4",
    hotelId: "hotel-5",
    hotelName: "Hôtel Sunset Beach",
    amount: 20000,
    currency: "XOF",
    status: "failed",
    paymentMethod: "mobile-money",
    createdAt: "2025-04-01T11:00:00",
    description: "Abonnement Multi - Avril 2025",
  },
  {
    id: "pay-5",
    hotelId: "hotel-6",
    hotelName: "Petit Hôtel Central",
    amount: 10000,
    currency: "XOF",
    status: "succeeded",
    paymentMethod: "mobile-money",
    createdAt: "2025-05-10T09:45:00",
    description: "Abonnement Essentiel - Mai 2025",
  },
  {
    id: "pay-6",
    hotelId: "hotel-1",
    hotelName: "Hôtel Ivoire Palace",
    amount: 35000,
    currency: "XOF",
    status: "succeeded",
    paymentMethod: "mobile-money",
    createdAt: "2025-04-01T10:30:00",
    description: "Abonnement Premium - Avril 2025",
  },
  {
    id: "pay-7",
    hotelId: "hotel-4",
    hotelName: "Grand Hôtel Cocody",
    amount: 35000,
    currency: "XOF",
    status: "succeeded",
    paymentMethod: "card",
    createdAt: "2025-04-01T08:15:00",
    description: "Abonnement Premium - Avril 2025",
  },
]

export const saasStats: SaasStats = {
  totalHotels: 156,
  activeHotels: 142,
  trialHotels: 8,
  suspendedHotels: 6,
  totalRevenue: 45680000,
  monthlyRecurringRevenue: 3250000,
  totalReservations: 52840,
  totalRooms: 2145,
  planDistribution: {
    essentiel: 68,
    multi: 52,
    premium: 36,
  },
}

export const saasFeatures: SaasFeature[] = [
  {
    id: "feat-1",
    name: "Gestion des chambres",
    description: "Créer, modifier et gérer les chambres de l'hôtel",
    enabled: true,
    plans: ["essentiel", "multi", "premium"],
    createdAt: "2024-01-01",
  },
  {
    id: "feat-2",
    name: "Réservations en ligne",
    description: "Recevoir et gérer les réservations depuis le site web",
    enabled: true,
    plans: ["essentiel", "multi", "premium"],
    createdAt: "2024-01-01",
  },
  {
    id: "feat-3",
    name: "Facturation automatique",
    description: "Génération automatique des factures avec TVA",
    enabled: true,
    plans: ["essentiel", "multi", "premium"],
    createdAt: "2024-01-01",
  },
  {
    id: "feat-4",
    name: "Multi-établissements",
    description: "Gérer plusieurs hôtels depuis un seul compte",
    enabled: true,
    plans: ["multi", "premium"],
    createdAt: "2024-01-01",
  },
  {
    id: "feat-5",
    name: "Rapports avancés",
    description: "Statistiques détaillées et exports CSV/PDF",
    enabled: true,
    plans: ["multi", "premium"],
    createdAt: "2024-02-15",
  },
  {
    id: "feat-6",
    name: "Site web vitrine",
    description: "Créer un site web pour présenter l'hôtel",
    enabled: true,
    plans: ["premium"],
    createdAt: "2024-01-01",
  },
  {
    id: "feat-7",
    name: "API & Intégrations",
    description: "Accès API pour intégration avec des systèmes tiers",
    enabled: true,
    plans: ["premium"],
    createdAt: "2024-03-01",
  },
  {
    id: "feat-8",
    name: "Support prioritaire",
    description: "Assistance téléphonique et réponse sous 2h",
    enabled: true,
    plans: ["premium"],
    createdAt: "2024-01-01",
  },
  {
    id: "feat-9",
    name: "Mode hors-ligne",
    description: "Continuer à travailler sans connexion internet",
    enabled: false,
    plans: ["essentiel", "multi", "premium"],
    createdAt: "2025-04-01",
  },
  {
    id: "feat-10",
    name: "Intelligence artificielle",
    description: "Prédiction des réservations et tarification dynamique",
    enabled: false,
    plans: ["premium"],
    createdAt: "2025-05-01",
  },
]
